name: Backend-CI

on:
  push:
    branches: [ "main", "backend/fix/cicd" ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BE_HOST }}
          key: ${{ secrets.BE_KEY }}
          port: ${{ secrets.BE_PORT }}
          username: ${{ secrets.BE_USERNAME }}
          script: |
            echo "${{ secrets.APPLICATION_PROD }}" > ${{ secrets.TCP_AGENDA_ROOT }}/service/TCP-Agenda/config/application-prod.yml
            ${{ secrets.TCP_AGENDA_ROOT }}/script/deploy.sh
